# Generated by Django 5.2.10 on 2026-02-10 07:51

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('codigo', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField()),
                ('url_juego', models.URLField()),
                ('genero', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('publicador', models.CharField(max_length=100)),
                ('desarrollador', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('perfil_freetogame', models.URLField()),
                ('categorias', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'juegos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('codigo', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('juego_id', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'rankings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
