# Generated by Django 5.2.10 on 2026-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videogames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='categoria_nombre',
            field=models.CharField(default='General', max_length=150),
        ),
        migrations.AddField(
            model_name='ranking',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
