# Generated by Django 5.2.10 on 2026-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videogames', '0002_ranking_categoria_nombre_ranking_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={},
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='juego',
            name='valoraciones_usuarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ranking',
            name='tier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterModelTable(
            name='ranking',
            table=None,
        ),
    ]
