# Generated by Django 5.2.10 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videogames', '0003_alter_ranking_options_remove_ranking_comentario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('usuario', 'categoria_nombre')},
        ),
        migrations.AddField(
            model_name='ranking',
            name='datos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='categoria_nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='ranking',
            table='rankings',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='juego_id',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='tier',
        ),
    ]
